/**
 * Turning entity pages and documents into MDX.
 */

import {
  Annotation,
  EntityDocument,
  EntityPage,
  InputOutput,
  Property,
  getIconUrl,
  getPageRelativePath,
} from "./model";
import { LastUpdate } from "./last-update";
import { sanitizeInput, sanitizeMetaDescription } from "./sanitize";

const AutogeneratedNotice = [
  "{/*",
  "!!!!!!",
  "THIS PAGE IS AUTOGENERATED FROM GAME FGD DEFINITIONS!",
  "DO NOT EDIT MANUALLY!",
  "!!!!!!",
  "",
  "In order to make edits, you can make an annotation file in /fgd_dump_overrides",
  "*/}",
].join("\n");

export function pageMdx(page: EntityPage): string {
  let propertiesString = "";

  if (page.Properties.length > 0) {
    propertiesString = detailsHeader("Keyvalues");

    for (const property of page.Properties) {
      propertiesString += propertyMdx(property);
    }

    propertiesString += "\n </details>";
  }

  let inputsString = "";
  let outputsString = "";

  const inputs = page.InputOutputs.filter((inputOutput) => inputOutput.Type === "Input");
  const outputs = page.InputOutputs.filter((inputOutput) => inputOutput.Type === "Output");

  if (inputs.length > 0) {
    inputsString = detailsHeader("Inputs");

    for (const input of inputs) {
      inputsString += inputOutputMdx(input);
    }

    inputsString += "\n </details>";
  }

  if (outputs.length > 0) {
    outputsString = detailsHeader("Outputs");

    for (const output of outputs) {
      outputsString += inputOutputMdx(output);
    }

    outputsString += "\n </details>";
  }

  let iconText = "";
  const iconUrl = getIconUrl(page);
  if (iconUrl !== null) {
    iconText = `<img src={"${iconUrl}"} alt="${page.Name ?? ""} icon" style={{height: '80px'}} />\n`;
  }

  return [
    "---",
    "hide_table_of_contents: true",
    // this page exists to be imported into the entity's document as one of its game tabs, on its
    // own it is a headless slab of keyvalues that should not be turning up in search results
    "unlisted: true",
    "---",
    "",
    AutogeneratedNotice,
    "",
    iconText,
    page.EntityType !== null ? `${page.EntityType} Entity` : "",
    page.PageAnnotation !== null ? annotationMdx(page.PageAnnotation) : "",
    sanitizeInput(page.Description ?? ""),
    "",
    propertiesString,
    inputsString,
    outputsString,
  ].join("\n");
}

export function documentMdx(document: EntityDocument, lastUpdate: LastUpdate | null = null): string {
  let tabImports = "";
  let tabs = "";
  let isLegacy = false;
  let isNonFGD = false;

  let sidebarClass = "";

  // used for embed description and image, can only pick from one game.
  let bestDescription = "";
  let bestIcon = "";

  for (const page of document.Pages) {
    // i shouldnt have to wonder why this needs toUpperCase() to render the page in the tab, yet here we are!
    const gameName = page.Game!;
    tabImports += `import ${gameName.toUpperCase()}Page from '@site/src/pages/Entities/${getPageRelativePath(page)}';\n`;

    tabs += `    ${gameName} = {<${gameName.toUpperCase()}Page/>}\n`;

    //TODO: sidebarClass will just override right now, figure out a better way to handle this

    // treat the document as legacy if any page has the legacy tag
    if (page.Legacy) {
      isLegacy = true;
      sidebarClass = "legacy_item";
    }

    // treat the document as non FGD if any page has the non FGD tag
    if (page.NonFGD) {
      isNonFGD = true;
      sidebarClass = "nonFGD_item";
    }

    const description = page.Description ?? "";

    if (description.length > bestDescription.length) {
      bestDescription = description;
    }

    // any game's icon will do, they are near always the same image
    if (bestIcon.length === 0) {
      bestIcon = getIconUrl(page) ?? "";
    }
  }

  return [
    "---",
    "hide_table_of_contents: true",
    sidebarClass.length > 0 ? `sidebar_class_name: ${sidebarClass}` : "",
    "custom_edit_url: /HowToEdit/entity-page-info",
    // JSON.stringify keeps quotes in the description valid YAML
    `description: ${JSON.stringify(sanitizeMetaDescription(bestDescription))}`,
    bestIcon.length > 0 ? `image: ${bestIcon}` : "",
    // JSON.stringify so quotes or colons in an author name stay valid YAML
    lastUpdate !== null ? `last_update:\n  date: ${JSON.stringify(lastUpdate.date)}\n  author: ${JSON.stringify(lastUpdate.author)}` : "",
    "---",
    "",
    AutogeneratedNotice,
    "",
    "import GameTabs from '@site/src/components/GameTabs'",
    "import '@site/src/css/tabs.css';",
    "",
    `# ${document.Name}`,
    "",
    isNonFGD ? annotationMdx({ Message: null, Type: "nonFGD", InternalName: null }) : "",
    isLegacy ? annotationMdx({ Message: null, Type: "legacy", InternalName: null }) : "",
    "",
    tabImports,
    "",
    "<GameTabs",
    tabs,
    "/>",
    "",
  ].join("\n");
}

export function annotationMdx(annotation: Annotation): string {
  // an annotation with no type still has something to say, note is the neutral admonition
  return [`   :::${annotation.Type ?? "note"}`, `   ${annotation.Message ?? ""}`, "   :::"].join("\n");
}

function propertyMdx(property: Property): string {
  // hack to get spawnflags to display properly, for some reason the friendly name is empty for these
  const friendlyName =
    property.InternalName === "spawnflags" ? "Spawnflags" : (property.FriendlyName ?? "");

  let propertyString = `- **${friendlyName}** (\`${property.InternalName ?? ""}\`) \\<\`${property.VariableType ?? ""}\`\\>`;

  if (property.Description) {
    propertyString += `\\\n${property.Description}`;
  }

  for (const annotation of property.Annotations) {
    propertyString += `\n${annotationMdx(annotation)}`;
  }

  let options = "";

  for (const option of property.Options) {
    options += `  - ${option.Name ?? ""}`;

    if (option.Key !== null) {
      options += ` (\`${option.Key}\`)`;
    }

    options += option.Description ? `\\\n    ${option.Description}\n` : "\n";
  }

  if (options.length > 0) {
    propertyString += `\n${options}`;
  }

  return `${propertyString}\n\n`;
}

function inputOutputMdx(inputOutput: InputOutput): string {
  let inputOutputString = `- ${inputOutput.Name ?? ""} \\<\`${inputOutput.VariableType ?? ""}\`\\>`;

  if (inputOutput.Description) {
    inputOutputString += `\\\n${inputOutput.Description}`;
  }

  return `${inputOutputString}\n\n`;
}

function detailsHeader(title: string): string {
  return `<details open>\n<summary><h2>${title}</h2></summary>\n`;
}
