/**
 * Turning entity pages and documents into MDX. Port of the GetMDXText methods in
 * EntityPage.cs and EntityDocument.cs.
 *
 * Those are C# raw string literals sitting in CRLF sources, so every line that comes from a
 * template ends CRLF while the fragments the code appends with "\n" stay LF. Both are
 * reproduced exactly, otherwise every generated file would show up as changed the first time
 * either tool runs after the other.
 */

import {
  Annotation,
  EntityDocument,
  EntityPage,
  InputOutput,
  Property,
  getIconUrl,
  getPageRelativePath,
} from "./model";
import { sanitizeInput } from "./sanitize";

const Newline = "\r\n";

const AutogeneratedNotice = [
  "{/*",
  "!!!!!!",
  "THIS PAGE IS AUTOGENERATED FROM GAME FGD DEFINITIONS!",
  "DO NOT EDIT MANUALLY!",
  "!!!!!!",
  "",
  "In order to make edits, you can make an annotation file in /fgd_dump_overrides",
  "*/}",
].join(Newline);

export function pageMdx(page: EntityPage): string {
  let propertiesString = "";

  if (page.Properties.length > 0) {
    propertiesString = detailsHeader("Keyvalues");

    for (const property of page.Properties) {
      propertiesString += propertyMdx(property);
    }

    propertiesString += "\n </details>";
  }

  let inputsString = "";
  let outputsString = "";

  const inputs = page.InputOutputs.filter((inputOutput) => inputOutput.Type === "Input");
  const outputs = page.InputOutputs.filter((inputOutput) => inputOutput.Type === "Output");

  if (inputs.length > 0) {
    inputsString = detailsHeader("Inputs");

    for (const input of inputs) {
      inputsString += inputOutputMdx(input);
    }

    inputsString += "\n </details>";
  }

  if (outputs.length > 0) {
    outputsString = detailsHeader("Outputs");

    for (const output of outputs) {
      outputsString += inputOutputMdx(output);
    }

    outputsString += "\n </details>";
  }

  let iconText = "";
  const iconUrl = getIconUrl(page);
  if (iconUrl !== null) {
    iconText = `<img src={"${iconUrl}"} alt="${page.Name} icon" style={{height: '80px'}} />\n`;
  }

  return [
    "---",
    "hide_table_of_contents: true",
    "---",
    "",
    AutogeneratedNotice,
    "",
    iconText,
    page.EntityType !== null ? `${page.EntityType} Entity` : "",
    page.PageAnnotation !== null ? annotationMdx(page.PageAnnotation) : "",
    sanitizeInput(page.Description),
    "",
    propertiesString,
    inputsString,
    outputsString,
  ].join(Newline);
}

export function documentMdx(document: EntityDocument): string {
  let tabImports = "";
  let tabs = "";
  let isLegacy = false;
  let isNonFGD = false;

  let sidebarClass = "";

  // used for embed description and image, can only pick from one game.
  let bestDescription = "";
  let bestIcon = "";

  for (const page of document.Pages) {
    // i shouldnt have to wonder why this needs toUpperCase() to render the page in the tab, yet here we are!
    const gameName = page.Game!.fileSystemName;
    tabImports += `import ${gameName.toUpperCase()}Page from '@site/src/pages/Entities/${getPageRelativePath(page)}';\n`;

    tabs += `    ${gameName} = {<${gameName.toUpperCase()}Page/>}${Newline}`;

    //TODO: sidebarClass will just override right now, figure out a better way to handle this

    // treat the document as legacy if any page has the legacy tag
    if (page.Legacy) {
      isLegacy = true;
      sidebarClass = "legacy_item";
    }

    // treat the document as non FGD if any page has the non FGD tag
    if (page.NonFGD) {
      isNonFGD = true;
      sidebarClass = "nonFGD_item";
    }

    if (page.Description.length > bestDescription.length) {
      bestDescription = page.Description;
    }

    // any game's icon will do, they are near always the same image
    if (bestIcon.length === 0) {
      bestIcon = getIconUrl(page) ?? "";
    }
  }

  return [
    "---",
    "hide_table_of_contents: true",
    sidebarClass.length > 0 ? `sidebar_class_name: ${sidebarClass}` : "",
    "custom_edit_url: /HowToEdit/entity-page-info",
    `description: "${sanitizeInput(bestDescription)}"`,
    bestIcon.length > 0 ? `image: ${bestIcon}` : "",
    "---",
    "",
    AutogeneratedNotice,
    "",
    "import GameTabs from '@site/src/components/GameTabs'",
    "import '@site/src/css/tabs.css';",
    "",
    `# ${document.Name}`,
    "",
    isNonFGD ? annotationMdx({ Message: "", Type: "nonFGD", InternalName: "" }) : "",
    isLegacy ? annotationMdx({ Message: "", Type: "legacy", InternalName: "" }) : "",
    "",
    tabImports,
    "",
    "<GameTabs",
    tabs,
    "/>",
    "",
  ].join(Newline);
}

export function annotationMdx(annotation: Annotation): string {
  return [`   :::${annotation.Type}`, `   ${annotation.Message}`, "   :::"].join(Newline);
}

function propertyMdx(property: Property): string {
  // hack to get spawnflags to display properly, for some reason the friendly name is empty for these
  const friendlyName =
    property.InternalName === "spawnflags" ? "Spawnflags" : property.FriendlyName;

  let propertyString = `- **${friendlyName}** (\`${property.InternalName}\`) \\<\`${property.VariableType ?? ""}\`\\>`;

  if (property.Description.length > 0) {
    propertyString += `\\\n${property.Description}`;
  }

  for (const annotation of property.Annotations) {
    propertyString += `\n${annotationMdx(annotation)}`;
  }

  let options = "";

  for (const option of property.Options) {
    options += `  - ${option.Name}`;

    if (option.Key !== null) {
      options += ` (\`${option.Key}\`)`;
    }

    options += option.Description.length > 0 ? `\\\n    ${option.Description}\n` : "\n";
  }

  if (options.length > 0) {
    propertyString += `\n${options}`;
  }

  return `${propertyString}\n\n`;
}

function inputOutputMdx(inputOutput: InputOutput): string {
  return `- ${inputOutput.Name} \\<\`${inputOutput.VariableType ?? ""}\`\\>\\\n${inputOutput.Description}\n\n`;
}

function detailsHeader(title: string): string {
  return `<details open>${Newline}<summary><h2>${title}</h2></summary>${Newline}`;
}
